source 'https://rubygems.org'

gem 'json'
gem 'pry'
gem 'telegram-bot-ruby', require: 'telegram/bot'
gem 'nokogiri'
gem 'sequel'
gem 'sqlite3', group: 'development'
gem 'rss'
gem 'dotenv', require: 'dotenv/load'
